[project]
name = "migrations"
version = "0.1.0"
dependencies = [
    "alembic==1.15.1",
    "asyncpg==0.31.0",
    "msgspec==0.20.0",
    "python-dotenv==1.0.1",
    "sqlalchemy==2.0.46",
]

[tool.uv]
package = false
